### ISSUE TITLE
question about data perturbation

### ISSUE THREAD

**Issue by 943fansi** [xuhongzuo/couta#5]
Hello, @xuhongzuo. This is a great work. I am interested with `data perturbation`(which also called data augmentation in other paper). Data augmentation is a popular work, and this technique is often used in contrastive learning. I noticed that this is used in recent time series anomaly detection work, such as [COCA](https://github.com/ruiking04/COCA), [TFAD](https://github.com/DAMO-DI-ML/CIKM22-TFAD). In the paper, you use several simple transformations to generate abnormal samples. Where is the code for this processing?

**Comment by xuhongzuo** [comment]
Great to see u here!

Please see the `create_batch_neg` function in `src/algorithms/couta_algo.py`.

**Comment by 943fansi** [comment]
@xuhongzuo Thanks.

**Comment by 943fansi** [comment]
@xuhongzuo Why not use 1 as a unified anomaly label, but use 1, 2, and 3 to represent `collective anomalies`, `contextual anomalies`, and `point anomalies`respectively? Does this have any impact when doing test evaluation, does the label value represent the importance of the anomaly, and can the anomaly score reflect the type of anomaly?

**Comment by xuhongzuo** [comment]
You find an exceptionally good point! 

There is a parameter `return_mul_label` in this function. We set it as False in our default settings. 
During the development of this model, we would like to see whether hierarchical labeling with ordinal regression or multi-class classification can work better than simply binary classification or regression to two extreme values. 

Sadly, the empirical results show this modification may fail to bring significantly better results on our datasets. But personally, I think fine-grained labels may give the network clear guidance, this idea is worthy to be explored by investigating new labeling strategies. 

Thanks!
